disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ondřej Honus"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo-light.png" 
  secondaryLogo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ 

[params.author]
  name = "Ondřej Honus"
  email = "ondrejhonus@pm.me"
  image = "img/author.png"
  imageQuality = 96
  headline = "Computer Science Student"
  bio = """Hi, I'm Ondřej Honus, a student and a developer from the Czech Republic. 
  I'm interested in programming, web applications, making music and cooking. 
  I'm currently learning C++, Python and Golang."""
  links = [
     { email = "mailto:ondrejhonus@pm.me" },
#     { link = "https://ondrejhonus.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/ondrejhonus" },
     { gitlab = "https://gitlab.com/ondrejhonus" },
     { recipes = "https://veg.ondrejhonus.com" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/ondrejhonus" },
     { itch-io = "https://qwerti.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
     { lastfm = "https://last.fm/user/qwerticek" },
     { linkedin = "https://linkedin.com/in/ondřej-honus-42405935a" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
